### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by pavlovt** [fuse-box/react-example#6]
Hi, 
I downloaded this project (version 1.0.0) and executed commands (on Windows 7, Node v7.5.0):
- npm install
- node fuse.js
node server has started without any errors but when I open the project in latest Chrome(http://localhost:4444/) and the result was:
- white screen
- errors in dev console:
  - Uncaught TypeError: Cannot read property 'connect' of undefined
  - GET http://localhost:4444/fusebox-hot-reload 404 (Not Found)

I had the same problem trying to run the other seed projects (vuejs, angular 2) with the same effect.
Am I doing something wrong?

**Comment by nchanged** [comment]
Hi!
Could you show your logs please?
```
      todo/todo.model.js
      todo/todo-list.component.html
      todo/todo-filter.pipe.js
      todo/todo-item.component.js
      todo/todo-item.component.html
└── fusebox-hot-reload (1 files) 1.2 kB
└── fusebox-websocket (1 files) 2.5 kB
└── events (1 files) 9.8 kB
└── core-js (81 files) 57.2 kB
└── zone.js (1 files) 83.3 kB
└── @angular/platform-browser-dynamic (1 files) 7.1 kB
└── @angular/compiler (1 files) 1.1 MB
└── @angular/core (1 files) 450.3 kB
└── rxjs (70 files) 148.7 kB
└── @angular/platform-browser (1 files) 166.1 kB
└── @angular/common (1 files) 133.8 kB
└── @angular/forms (1 files) 224.4 kB
└── @angular/material (1 files) 739.6 kB
└── @angular/http (1 files) 78.3 kB
└── lodash (1 files) 527.1 kB

    Bundle
    Size: 3.7 MB
    Time: 1s 723ms
```

**Comment by nchanged** [comment]
And could you clean the cache please?

**Comment by pavlovt** [comment]
Thanks for the quick response!
It is working now - possible problems are:
- I had node 6.9 when I ran npm install
- later I installed node 7.5 but did not reinstall node_modules
- probably node 7.x is required and I missed that - if it is so it will be good to include it in this project's documentation.

What I did to make it work:
- delete node_modules and run npm install again
- delete .fusebox/cache/*
- run node fuse.js

**Comment by nchanged** [comment]
It's probably related to .fusebox folder, sometimes it bugs up. But we are working on improvements!
